---
spring:
  application:
    name: spring-cloud-producer
  profiles: producer1
server:
  port: 10010
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/
---
spring:
  application:
    name: spring-cloud-producer
  profiles: producer2
server:
  port: 10020
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/
---
spring:
  application:
    name: spring-cloud-producer
  profiles: producer3
server:
  port: 10030
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/